---
name: "IMDb Ratings"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "<template>"
targetAbi: "10.11.7.0"
framework: "<template>"
overview: "Ratings from IMDb"
description: >
  Fetch IMDb ratings for movies, TV shows and episodes from the IMDb official source and use as community ratings in Jellyfin
category: "General"
owner: "verybadsoldier"
artifacts:
- "Jellyfin.Plugin.ImdbRatings.dll"
changelog: >
  changelog
